### ISSUE TITLE
Unification proposal

### ISSUE THREAD

**Issue by yasuyuky** [benogle/autocomplete-clang#1]
Hello. 
I'm the author of https://atom.io/packages/autocomplete-clang
Thanks for your reference to my autocomplete-clang repository and respect the license.

I've been thinking about using `autocomplete-plus` to provide completion by clang.
Using `autocomplete-plus` will simplify code and reduce the cost for the maintenance.
And now `autocomplete-plus` is one of the bundled packages of Atom.

Your proof of the concept looks nice for me. But it is not published.
(Forked version(?) https://github.com/BurningMind/autocomplete-plus-clang/blob/master/lib/clang-provider.coffee is published)

If you have a plan to publish, I guess that unifying the package is better for the users.
Unfortunately, the name `autocomplete-clang` collision occurred.
There are some ways for publish.
1. I change the package-name and you publish this package. 
   (If you wanted to publish this repository itself)
2. You make the PR of change to use `autocomplete-plus`
   (if you need administrative permission of the package, It's OK)
3. You publish this repository with another name and I keep my package as the not using `-plus`

I prefer the second option.
https://atom.io/packages/autocomplete-clang downloaded over 13K times and have many users.
I cannot handle all the issue. It's expanded too match for me. 
If possible, community base development could be better.

**Comment by benogle** [comment]
Definitely in for unification.

> I've been thinking about using autocomplete-plus to provide completion by clang.
> Using autocomplete-plus will simplify code and reduce the cost for the maintenance.
> And now autocomplete-plus is one of the bundled packages of Atom.

Yes. The second option sounds ok.

The one caveat is that I do not have time to do this work right now. Do you have time to convert your package to use autocomplete-plus? If you convert it to use ac+, then I (or the atom org) can to take ownership after that.

**Comment by yasuyuky** [comment]
> Yes. The second option sounds ok.

I'm grad to hear that.

> Do you have time to convert your package to use autocomplete-plus? 
> If you convert it to use ac+, then I (or the atom org) can to take ownership after that.

OK, I'd try it. Thank you.
